#spring:
#  application:
#    name: keycloak
#  security:
#    oauth2:
#      client:
#        registration:
#          oauth2-demo-thymeleaf-client:
#            client-id: oauth2-demo-thymleaf-client
#            client-secret: lrpSEv5GcxfHC4edtLvRhFvxc9Jx6rws
#            scope:
#              - openid
#              - profile
#              - roles
#            authorization-grant-type: authorization_code
#            redirect-uri: http://localhost:8080/login/oauth2/code/oauth2-demo-thymleaf-client
#        provider:
#          oauth2-demo-thymeleaf-client:
#            issuer-uri: http://localhost:8181/realms/oauth2-demo-realm
#

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8181/realms/oauth2-demo-realm/protocol/openid-connect/certs
